tsbd:
  enabled: true
  tag: "__TCC__"
  disableauthz: false

oap:
  enabled: true
  # Set by bash scripts in deploy folder of tetrate repo 
  tag: "__OAP__"
  token: ""
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
  elasticsearch:
    host: "__HOST__"
    port: 8443
  analysis: reg-agent-mesh
  logLevel: WARN
  enabledPackedDownsampling: false
  dayStep: 1
  externalServices:
    # For SPM metadata service.
    metadata:
      enabled: false
    # For SPM configuration service (DCS).
    configuration:
      enabled: false
      clusterName: default
      period: 60
    # Optionally add (default) webhook uri here.
    webhook:
      uri: ""

tracing:
  enabled: true
  elasticsearch:
    host: "__HOST__"
    port: 8443
  zipkin:
    #token: ""
    env:
      STORAGE_TYPE: "elasticsearch"
      # Zipkin sends to local envoy which forwards to TCC elastic search.
      ES_HOSTS: "http://127.0.0.1:9200"      

global:
  tcc:
    enabled: true
    host: "__HOST__"
    port: 8443
    tenant: "__TENANT__"
    cluster: "__CLUSTER__"
    environment: "__ENV__"

  hub: "__HUB__"
  tag: "__ISTIO__"
  controlPlaneSecurityEnabled: true
  disablePolicyChecks: true
  enableTracing: true
  configValidation: false
  defaultPodDisruptionBudget:
    enabled: false

  elasticsearch:
    user: ""
    password: ""
    ssl:
      enabled: true
