global:
  omitSidecarInjectorConfigMap: true
  istioNamespace: istio-system
  controlPlaneSecurityEnabled: true
  hub: "__HUB__"
  tag: "__ISTIO__"
  defaultPodDisruptionBudget:
    enabled: false

  tcc:
    enabled: true
    host: "__HOST__"
    port: 8443
    tenant: "__TENANT__"
    cluster: "__CLUSTER__"
    environment: "__ENV__"

  proxy:
    envoyAccessLogService:
      enabled: true
      host: oap.istio-system
      port: 11800

gateways:
  enabled: true

  istio-ingressgateway:
    enabled: false
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
      tcc: clustergateway
    sds:
      enabled: true
    env:
      ISTIO_META_ROUTER_MODE: ""
    ports:
    - port: 80
      targetPort: 80
      name: http2
    - port: 443
      name: https
    secretVolumes: 

  istio-egressgateway:
    enabled: false

  tcc-app-gateway:
    enabled: false
    labels:
      app: istio-appgateway
      tcc: appgateway
    sds:
      enabled: true
      image: node-agent-k8s
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    cpu:
      targetAverageUtilization: 80
    loadBalancerIP: ""
    loadBalancerSourceRanges: {}
    externalIPs: []
    serviceAnnotations: {}
    podAnnotations: {}
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    #externalTrafficPolicy: Local #change to Local to preserve source IP or Cluster for default behaviour or leave commented out
    ports:
      ## You can add custom gateway ports
    - port: 80
      targetPort: 80
      name: http2
      # nodePort: 31380
    - port: 443
      name: https
      # nodePort: 31390
    secretVolumes: {}

# all other components should be disabled except the gateways
security:
  enabled: false

sidecarInjectorWebhook:
  enabled: false

galley:
  enabled: false

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

pilot:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false

tracing:
  enabled: false

kiali:
  enabled: false

certmanager:
  enabled: false

oap:
  enabled: false

regsource:
  enabled: false
