apiVersion: apps/v1
kind: Deployment
metadata:
  name: oap-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: oap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oap
  template:
    metadata:
      labels:
        app: oap
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: oap-service-account
      initContainers:
      - name: override-config
        image: {{ .Values.global.hub }}/envsubst:v1.0
        command: ['/bin/sh']
        args: ['-c', 'for file in $(ls -A /tmpl); do envsubst < /tmpl/$file > /config/$file; done']
        volumeMounts:
          - name: tmpl
            mountPath: /tmpl
          - name: config
            mountPath: /config
        envFrom:
        - secretRef:
            name: oap-token
      containers:
      - name: oap
        image: {{ .Values.global.hub }}/spm-user:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        - containerPort: 1234
          name: http-monioring
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: JAVA_OPTS
          value: -Xmx4096M -Dmode=no-init
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_CLUSTER_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SW_EXPORTER_GRPC_HOST
          value: localhost
        - name: SW_EXPORTER_GRPC_PORT
          value: "21800"
        - name: SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS
          value: {{ .Values.analysis }}
        - name: SW_SPM_CLUSTER_NAME
          value: {{ .Values.global.tcc.cluster }}
        - name: SW_SPM_ENV_NAME
          value: {{ .Values.global.tcc.environment }}
        - name: SW_ENVOY_METRIC_ALS_REG_AGENT_HOST
          value: tsbd
        - name: SW_ENVOY_METRIC_ALS_REG_AGENT_PORT
          value: "9080"
        {{- if .Values.externalServices.metadata.enabled }}
        - name: SW_STORAGE
          value: tsb-es
        - name: SW_TSB_HOST
          value: localhost
        - name: SW_TSB_PORT
          value: "9080"
        {{- end }}
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: localhost:9200
        - name: SW_ES_USER
          value: {{ .Values.global.elasticsearch.user }}
        - name: SW_ES_PASSWORD
          value: {{ .Values.global.elasticsearch.password }}
        - name: SW_ES_SECRETS_MANAGEMENT_FILE
          value: {{ .Values.elasticsearch.secretFile }}
        - name: SW_STORAGE_ENABLE_PACKED_DOWNSAMPLING
          value: "{{ .Values.enabledPackedDownsampling }}"
        - name: SW_STORAGE_DAY_STEP
          value: "{{ .Values.dayStep }}"
        {{- if .Values.externalServices.configuration.enabled }}
        - name: SW_CONFIGURATION
          value: grpc
        - name: SW_CONFIGURATION_GRPC_HOST
          value: localhost
        - name: SW_CONFIGURATION_GRPC_PORT
          value: "9081"
        - name: SW_CONFIGURATION_GRPC_PERIOD
          value: "{{ .Values.externalServices.configuration.period }}"
        - name: SW_CONFIGURATION_GRPC_CLUSTER_NAME
          value: "{{ .Values.externalServices.configuration.clusterName }}"
        {{- end }}
        volumeMounts:
        - mountPath: /skywalking/ext-config
          name: config
      - name: istio-proxy
{{- if contains "/" .Values.global.proxy.image }}
        image: "{{ .Values.global.proxy.image }}"
{{- else }}
        image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
{{- end }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: [ "/usr/local/bin/envoy" ]
        args:
        - -c
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - envoy-proxy
        ports:
        - containerPort: 50001
        - containerPort: 9200
        volumeMounts:
        - mountPath: /etc/envoy/
          name: config
      volumes:
      - name: tmpl
        configMap:
          name: oap-config
      - name: config
        emptyDir: {}
